version: '3'

services:
  web_app:
    build: .
    expose:
      - "8080"
    env_file:
      - ./.env.prod

  nginx:
    container_name: socket_nginx
    build: containers/services/nginx
    ports:
      - "80:80"
    restart: always
    links:
      - web_app
    depends_on:
      - web_app
